// Copyright (c) 2026 Oleksii PELYKH
// SPDX-License-Identifier: MIT

// The Swift half of the config-set reject-detail cross-language pin (issue #1112).
//
// Two `Fixtures` entries carry a `detail` that is a VERBATIM copy of a message the Rust crate
// authors — `configSetErrorStaleKey` (serde's `deny_unknown_fields` message for `SetTunables`,
// which enumerates every settable key) and `configSetRejectedFleetRunwayInvalid`
// (`Config::validate`'s fleet-runway band rejection). The tests that consume those fixtures assert
// the client threads the daemon's own `detail` through instead of substituting a generic one, and
// they are green whether or not the copy is current: the fixture IS their oracle. So a stale copy
// still proved the plumbing, and nothing proved the fidelity the fixture exists for.
//
// Neither message exists as a literal in `src/` — the fleet band is `format!`-interpolated from
// `FLEET_RUNWAY_PLAUSIBLE_MAX_SECS` and the key enumeration is generated by serde's derive — so
// they cannot be grepped for. Both are free at runtime, so `src/config/settings.rs` emits them into
// `build/fixtures/config-set-reject-details.json` and pins that file to what the code produces;
// this file reads the SAME bytes. Neither surface can move alone: change a message and the Rust pin
// reddens until the golden is re-emitted, and re-emitting reddens THIS gate until the fixtures
// follow. Same mechanism as `WireGoldenTests` (issue #340) and `CrossSurfaceSeverityParityTests`
// (issue #768).
//
// The golden is read from the repo, not bundled: the fixtures deliberately stay inline literals in
// `Fixtures.swift`, and the path resolves from THIS source file's `#filePath`, so it works
// identically under `xcodebuild test` in CI and locally with no working-directory assumption.
// `build/fixtures/**` is in the `swift` CI path filter, so re-emitting re-runs this check.
//
// What this gate does NOT reach, in both directions. It compares the `detail` STRING, not the
// envelope around it — the reply shape is `ConfigWireTests`' subject. It does not cover serde's
// input-dependent ` at line N column M` suffix, which `configSetErrorStaleKey` has elided since
// #671 and still elides; the golden is emitted position-free to match. It does not cover
// `configSetRejectedInvalid`, whose doc claims only that `detail` names the field — it is a
// synthetic sample, not a copy, and its wording does not match `validate.rs`'s current message. It
// does not cover `SettingsTextMetricsTests.staleKeyDetail`, which is RECONSTRUCTED from
// `TunableField.allCases` as a deliberate lower bound rather than copied. And it does not cover
// prose: a doc comment quoting a band (as `SettingsModelTests` does) stays hand-maintained.

import XCTest

final class ConfigSetRejectDetailParityTests: XCTestCase {

    /// The committed golden's shape. Both fields are non-optional ON PURPOSE: a renamed or dropped
    /// key fails the decode loudly instead of defaulting to an empty string that would then compare
    /// equal to nothing and pass.
    private struct RejectDetails: Decodable {
        let configSetErrorStaleKey: String
        let configSetRejectedFleetRunwayInvalid: String
    }

    /// Just enough of a reply envelope to lift the copied string out of a fixture. Deliberately NOT
    /// `decodeConfigSetReply`: this gate is about the string, and routing it through the production
    /// decoder would make a decoder bug able to mask a drifted fixture.
    private struct DetailEnvelope: Decodable {
        let detail: String
    }

    /// Repo-root `build/fixtures/config-set-reject-details.json` resolved from this test file's own
    /// location — the same idiom as `WireGoldenTests`. Strips the filename then three directory
    /// levels (`Tests` → `menubar` → `apps`) to reach `<repo>/`.
    private static func goldenURL(file: StaticString = #filePath) -> URL {
        URL(fileURLWithPath: "\(file)")
            .deletingLastPathComponent()   // Tests/
            .deletingLastPathComponent()   // menubar/
            .deletingLastPathComponent()   // apps/
            .deletingLastPathComponent()   // <repo>/
            .appendingPathComponent("build/fixtures/config-set-reject-details.json")
    }

    private func committed() throws -> RejectDetails {
        let url = Self.goldenURL()
        let data = try Data(contentsOf: url)
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try decoder.decode(RejectDetails.self, from: data)
    }

    private func detail(of fixture: String, _ name: String) throws -> String {
        let data = try XCTUnwrap(fixture.data(using: .utf8), "\(name) is not UTF-8")
        return try JSONDecoder().decode(DetailEnvelope.self, from: data).detail
    }

    /// `configSetErrorStaleKey`'s `detail` is serde's key enumeration for `SetTunables`, so it goes
    /// stale on any settable ADDED or RENAMED — a far wider trigger than the fleet fixture's. This
    /// is the copy that had actually drifted when #1112 was filed.
    func testStaleKeyFixtureDetailMatchesTheRustGolden() throws {
        XCTAssertEqual(
            try detail(of: Fixtures.configSetErrorStaleKey, "configSetErrorStaleKey"),
            try committed().configSetErrorStaleKey,
            "configSetErrorStaleKey's detail drifted from the Rust-emitted golden — a settable was "
                + "added or renamed in SetTunables (src/config.rs). Re-run `cargo test -- --ignored "
                + "emit_config_set_reject_details_golden`, then paste the golden's "
                + "config_set_error_stale_key value into this fixture's detail"
        )
    }

    /// `configSetRejectedFleetRunwayInvalid`'s `detail` goes stale when `Config::validate`'s message
    /// changes — including a move of `FLEET_RUNWAY_PLAUSIBLE_MAX_SECS`, which the Rust side derives
    /// from the constant and this copy spells out as a literal. That is what issue #1076 hit.
    func testFleetRunwayFixtureDetailMatchesTheRustGolden() throws {
        XCTAssertEqual(
            try detail(of: Fixtures.configSetRejectedFleetRunwayInvalid,
                       "configSetRejectedFleetRunwayInvalid"),
            try committed().configSetRejectedFleetRunwayInvalid,
            "configSetRejectedFleetRunwayInvalid's detail drifted from the Rust-emitted golden — "
                + "Config::validate's fleet_runway_warn_secs rejection changed "
                + "(src/config/validate.rs). Re-run `cargo test -- --ignored "
                + "emit_config_set_reject_details_golden`, then paste the golden's "
                + "config_set_rejected_fleet_runway_invalid value into this fixture's detail"
        )
    }

    /// Non-degeneracy. Both assertions above would pass over a golden of two empty strings if the
    /// fixtures' details were empty too, and would pass over a golden whose two entries had been
    /// swapped. Anchor each on the token it must name — the offending KEY and the field name, never
    /// the part that drifts — so this is a liveness check, not a third copy of the messages.
    func testTheGoldenIsNotDegenerate() throws {
        let golden = try committed()
        XCTAssertTrue(
            golden.configSetErrorStaleKey.contains("session_trigger")
                && golden.configSetErrorStaleKey.contains("`poll_secs`"),
            "the golden's stale-key entry names neither the offending key nor a settable: "
                + golden.configSetErrorStaleKey)
        XCTAssertTrue(
            golden.configSetRejectedFleetRunwayInvalid.hasPrefix("fleet_runway_warn_secs"),
            "the golden's fleet-runway entry does not lead with its field: "
                + golden.configSetRejectedFleetRunwayInvalid)
    }
}
