// Copyright (c) 2026 Oleksii PELYKH
// SPDX-License-Identifier: MIT

// The Swift half of the config-set reject-detail cross-language pin (issue #1112).
//
// Three Swift copies hold a `detail` that is a VERBATIM copy of a message the Rust crate authors.
// Two are `Fixtures` entries — `configSetErrorStaleKey` (serde's `deny_unknown_fields` message for
// `SetTunables`, which enumerates every settable key) and `configSetRejectedFleetRunwayInvalid`
// (`Config::validate`'s fleet-runway band rejection). The tests that consume those fixtures assert
// the client threads the daemon's own `detail` through instead of substituting a generic one, and
// they are green whether or not the copy is current: the fixture IS their oracle. So a stale copy
// still proved the plumbing, and nothing proved the fidelity the fixture exists for.
//
// The third (issue #1248) is `SettingsTextMetricsTests.zeroTargetRemedyDetail`: `Config::validate`'s
// `target_max_session_usage = 0` remedy (issue #414), held as a BARE `detail` string rather than a
// canned reply because its consumer measures rendered WIDTH, not decoding. Same defect class, same
// reason nothing caught it — the copy was its own oracle. It stays in that file rather than moving
// to `Fixtures.swift`, which is deliberately free of XCTest and app-model dependencies while this
// string must read its two key names from `TunableField`; it is `static` only so this gate can
// reach it.
//
// None of the three exists as a literal in `src/` — the fleet band is `format!`-interpolated from
// `FLEET_RUNWAY_PLAUSIBLE_MAX_SECS`, the key enumeration is generated by serde's derive, and the
// zero-target remedy interpolates the submitted `session_ceiling` — so they cannot be grepped for.
// All three are free at runtime, so `src/config/settings.rs` emits them into
// `build/fixtures/config-set-reject-details.json` and pins that file to what the code produces;
// this file reads the SAME bytes. Neither surface can move alone: change a message and the Rust pin
// reddens until the golden is re-emitted, and re-emitting reddens THIS gate until the copies
// follow. Same mechanism as `WireGoldenTests` (issue #340) and `CrossSurfaceSeverityParityTests`
// (issue #768).
//
// The zero-target emitter passes `DEFAULT_SESSION_CEILING` explicitly rather than letting the test
// config's own ceiling stand, because that message interpolates whatever ceiling was submitted and
// the Swift copy states it models the shipped default. A MOVE of that constant therefore reddens
// this gate too — the half of that copy no message-text edit would disturb.
//
// The golden is read from the repo, not bundled: the Swift copies deliberately stay inline literals
// in their own files, and the path resolves from THIS source file's `#filePath`, so it works
// identically under `xcodebuild test` in CI and locally with no working-directory assumption.
// `build/fixtures/**` is in the `swift` CI path filter, so re-emitting re-runs this check.
//
// What this gate does NOT reach, in both directions. It compares the `detail` STRING, not the
// envelope around it — the reply shape is `ConfigWireTests`' subject. It does not cover serde's
// input-dependent ` at line N column M` suffix, which `configSetErrorStaleKey` has elided since
// #671 and still elides; the golden is emitted position-free to match. It does not cover
// `configSetRejectedInvalid`, whose doc claims only that `detail` names the field — it is a
// synthetic sample, not a copy, and its wording does not match `validate.rs`'s current message. It
// does not cover `SettingsTextMetricsTests.staleKeyDetail`, which is RECONSTRUCTED from
// `TunableField.allCases` as a deliberate lower bound rather than copied. And it does not cover
// prose: a doc comment quoting a band (as `SettingsModelTests` does on
// `testApplyFleetRunwayOutOfBandRejectedWithDaemonDetail`) stays hand-maintained.
//
// That last file needs one more word, because naming only its prose understates it (issue #1248).
// The SAME test also asserts the fleet message IN FULL — a second verbatim copy of it, in the
// `XCTAssertEqual` on `applyPhase`. That copy is NOT unguarded and needs no pin of its own: it is
// asserted against `Fixtures.configSetRejectedFleetRunwayInvalid`, which IS pinned here, so it
// reddens the moment that fixture follows a re-emitted golden. Guarded transitively, not
// hand-maintained — the distinction naming only the prose would blur.
//
// One thing this gate DOES now reach that it did not (issues #1248, #1254): the golden's own key
// set. `RejectDetails` below and the Rust `ConfigSetRejectDetails` it mirrors both IGNORE unknown
// JSON keys, so a fourth entry emitted Rust-side used to decode clean on both sides and be read by
// nobody, with every test green. `testTheGoldensKeysAreExactlyTheRejectDetailsFields` compares the
// golden's top-level keys against `RejectDetails`' own stored properties, so such an entry reddens
// instead. Read that scope exactly, because it is narrower than the name suggests: it proves those
// two sets are EQUAL, and says nothing about the assertions below. A field that has a golden entry
// but no `XCTAssertEqual` above passes it — measured, not assumed (issue #1254) — so "every entry
// is compared" still rests on the enumeration below, one test per key. What it does close is the
// direction that used to be open by construction: an entry can no longer be emitted and declared
// read while reaching no field at all.
//
// #1248 asserted that against `readKeys`, a hand-maintained `Set<String>` beside the struct rather
// than the struct itself, which left `readKeys` ⊋ `RejectDetails` passing: a name added there AND
// to the golden, with no field and no comparison, satisfied the check while leaving the entry
// unread — measured green across the whole suite (issue #1254). Two spellings are why it was
// written that way: `Mirror` yields camelCase labels and the golden is snake case. The bridge here
// is the DECODER's own `.convertFromSnakeCase`, not a hand-written converter, which would have
// been a third hand-maintained spelling in a file whose defect was the second one. `readKeys` is
// gone, so no third enumeration is left to drift.
//
// The two directions fail differently, which is what a maintainer actually sees. A golden entry
// reaching no field reddens THAT comparison and names it. A field with no golden entry never gets
// there: `committed()` fails to decode first, loudly, as it always has.
//
// Two further bounds on that key-set gate, both measured rather than assumed. It does not reach the
// RUST end of the same hole: `ConfigSetRejectDetails` (src/config/settings.rs) carries no
// `deny_unknown_fields`, and a golden holding an unread fourth key leaves that pin GREEN — only
// this side reddens. Reaching that end only matters for a hand-edited golden, which the repo
// already says to regenerate instead, so it is recorded here rather than closed. And it is a
// dedicated test rather than an unknown-key rejection inside `RejectDetails`' decode, which was the
// other way to close this: Swift has no `deny_unknown_fields`, so that route needs a hand-written
// `init(from:)` enumerating the very same key set — no more exhaustive-by-construction, and it
// would report a coverage gap as a DECODING failure in every test that touches `committed()`,
// burying which key is unread. This way one test reddens and names it.

import XCTest

final class ConfigSetRejectDetailParityTests: XCTestCase {

    /// The committed golden's shape. All three fields are non-optional ON PURPOSE: a renamed or
    /// dropped key fails the decode loudly instead of defaulting to an empty string that would then
    /// compare equal to nothing and pass. Unknown keys are the direction this shape does NOT catch —
    /// `testTheGoldensKeysAreExactlyTheRejectDetailsFields` below covers that one, by reflecting
    /// over these very properties: a field added here is picked up with no second declaration
    /// anywhere, which is the point (issue #1254).
    private struct RejectDetails: Decodable {
        let configSetErrorStaleKey: String
        let configSetRejectedFleetRunwayInvalid: String
        let zeroTargetRemedyDetail: String
    }

    /// Just enough of a reply envelope to lift the copied string out of a fixture. Deliberately NOT
    /// `decodeConfigSetReply`: this gate is about the string, and routing it through the production
    /// decoder would make a decoder bug able to mask a drifted fixture.
    private struct DetailEnvelope: Decodable {
        let detail: String
    }

    /// Accepts whatever key the decoder hands it, so `allKeys` below reports the object's real
    /// keys instead of a fixed set this file would have to enumerate.
    private struct AnyKey: CodingKey {
        let stringValue: String
        var intValue: Int? { nil }
        init?(stringValue: String) { self.stringValue = stringValue }
        init?(intValue: Int) { return nil }
    }

    /// A JSON object's top-level key names, taken from the keyed container so that the surrounding
    /// decoder's `keyDecodingStrategy` has already been applied to them.
    private struct TopLevelKeys: Decodable {
        let names: [String]
        init(from decoder: Decoder) throws {
            names = try decoder.container(keyedBy: AnyKey.self).allKeys.map(\.stringValue)
        }
    }

    /// Repo-root `build/fixtures/config-set-reject-details.json` resolved from this test file's own
    /// location — the same idiom as `WireGoldenTests`. Strips the filename then three directory
    /// levels (`Tests` → `menubar` → `apps`) to reach `<repo>/`.
    private static func goldenURL(file: StaticString = #filePath) -> URL {
        URL(fileURLWithPath: "\(file)")
            .deletingLastPathComponent()   // Tests/
            .deletingLastPathComponent()   // menubar/
            .deletingLastPathComponent()   // apps/
            .deletingLastPathComponent()   // <repo>/
            .appendingPathComponent("build/fixtures/config-set-reject-details.json")
    }

    /// The golden's top-level keys, in both spellings this file has to reconcile: as WRITTEN in
    /// the JSON (snake case), and as the DECODER produces them (camelCase, through the same
    /// `.convertFromSnakeCase` `committed()` sets). The second is the spelling `RejectDetails`'
    /// field names are matched against, so it is the one the gate below compares; the first is
    /// carried only so a failure can name the offender as the golden spells it.
    ///
    /// Read from a keyed container's `allKeys` rather than from a `[String: String]` decode, and
    /// that is not a style choice: the dictionary path does NOT apply the key strategy — measured
    /// on Swift 6.3.3, it hands the keys back unconverted — so it would compare snake case against
    /// camelCase field names and never match. Going through a container makes the bridge between
    /// the two spellings the decoder's OWN conversion step rather than a hand-written camel/snake
    /// helper, which would be a third hand-maintained spelling in a file whose defect (issue
    /// #1254) was the second one.
    private static func goldenKeys() throws -> (asWritten: [String], asDecoded: [String]) {
        let data = try Data(contentsOf: goldenURL())
        let converting = JSONDecoder()
        converting.keyDecodingStrategy = .convertFromSnakeCase
        return (
            asWritten: try JSONDecoder().decode(TopLevelKeys.self, from: data).names,
            asDecoded: try converting.decode(TopLevelKeys.self, from: data).names
        )
    }

    private func committed() throws -> RejectDetails {
        let url = Self.goldenURL()
        let data = try Data(contentsOf: url)
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try decoder.decode(RejectDetails.self, from: data)
    }

    private func detail(of fixture: String, _ name: String) throws -> String {
        let data = try XCTUnwrap(fixture.data(using: .utf8), "\(name) is not UTF-8")
        return try JSONDecoder().decode(DetailEnvelope.self, from: data).detail
    }

    /// `configSetErrorStaleKey`'s `detail` is serde's key enumeration for `SetTunables`, so it goes
    /// stale on any settable ADDED or RENAMED — a far wider trigger than the fleet fixture's. This
    /// is the copy that had actually drifted when #1112 was filed.
    func testStaleKeyFixtureDetailMatchesTheRustGolden() throws {
        XCTAssertEqual(
            try detail(of: Fixtures.configSetErrorStaleKey, "configSetErrorStaleKey"),
            try committed().configSetErrorStaleKey,
            "configSetErrorStaleKey's detail drifted from the Rust-emitted golden — a settable was "
                + "added or renamed in SetTunables (src/config.rs). Re-run `cargo test -- --ignored "
                + "emit_config_set_reject_details_golden`, then paste the golden's "
                + "config_set_error_stale_key value into this fixture's detail"
        )
    }

    /// `configSetRejectedFleetRunwayInvalid`'s `detail` goes stale when `Config::validate`'s message
    /// changes — including a move of `FLEET_RUNWAY_PLAUSIBLE_MAX_SECS`, which the Rust side derives
    /// from the constant and this copy spells out as a literal. That is what issue #1076 hit.
    func testFleetRunwayFixtureDetailMatchesTheRustGolden() throws {
        XCTAssertEqual(
            try detail(of: Fixtures.configSetRejectedFleetRunwayInvalid,
                       "configSetRejectedFleetRunwayInvalid"),
            try committed().configSetRejectedFleetRunwayInvalid,
            "configSetRejectedFleetRunwayInvalid's detail drifted from the Rust-emitted golden — "
                + "Config::validate's fleet_runway_warn_secs rejection changed "
                + "(src/config/validate.rs). Re-run `cargo test -- --ignored "
                + "emit_config_set_reject_details_golden`, then paste the golden's "
                + "config_set_rejected_fleet_runway_invalid value into this fixture's detail"
        )
    }

    /// `SettingsTextMetricsTests.zeroTargetRemedyDetail` is a BARE `detail` string, not a canned
    /// reply, so it is compared directly — there is no envelope to unwrap. It goes stale on any edit
    /// to `Config::validate`'s zero-target remedy AND on a move of `DEFAULT_SESSION_CEILING`, which
    /// that message interpolates and this copy spells out as a literal `1..=95` (issue #1248).
    func testZeroTargetRemedyMatchesTheRustGolden() throws {
        XCTAssertEqual(
            SettingsTextMetricsTests.zeroTargetRemedyDetail,
            try committed().zeroTargetRemedyDetail,
            "SettingsTextMetricsTests.zeroTargetRemedyDetail drifted from the Rust-emitted golden "
                + "— Config::validate's target_max_session_usage = 0 remedy changed, or "
                + "DEFAULT_SESSION_CEILING moved (src/config.rs). Re-run `cargo test -- --ignored "
                + "emit_config_set_reject_details_golden`, then paste the golden's "
                + "zero_target_remedy_detail value into that fixture"
        )
    }

    /// Issue #1248: coverage above is ENUMERATED — one test per entry — and nothing made it
    /// exhaustive. Both structs on this wire ignore unknown JSON keys, so an entry emitted
    /// Rust-side with no Swift copy pinned to it decoded clean and passed unread. Issue #1254: that
    /// check compared the golden against a hand-maintained name list beside `RejectDetails` rather
    /// than against the struct, so an entry could be emitted, listed as read, and still reach no
    /// field. This compares the golden's keys against the struct's own properties instead.
    ///
    /// Only one direction can fail HERE, by construction. `committed()` requires every field's key
    /// to be present, so by the time this comparison runs the fields are already a subset of the
    /// golden's keys, and the only difference that can remain is a golden entry reaching no field.
    /// The opposite case — a field with no golden entry — fails earlier, in that decode, and is not
    /// silent. Compare SETS rather than counts: a count is blind to a same-size rename.
    func testTheGoldensKeysAreExactlyTheRejectDetailsFields() throws {
        let keys = try Self.goldenKeys()

        // The conversion is the bridge, so prove first that it does not COLLAPSE two golden keys
        // onto one name — `foo_bar` and `fooBar` both convert to `fooBar`. A collapse would drop an
        // entry from the set below and hide precisely what this test exists to find.
        XCTAssertEqual(
            Set(keys.asDecoded).count, keys.asWritten.count,
            "two of the golden's keys convert to the same name, so the comparison below cannot see "
                + "them both. As written: \(keys.asWritten.sorted()). As decoded: "
                + "\(keys.asDecoded.sorted())"
        )

        let fields = Set(
            Mirror(reflecting: try committed()).children.map { $0.label ?? "<unlabelled>" })
        XCTAssertEqual(
            Set(keys.asDecoded), fields,
            "the committed golden holds entries that reach no `RejectDetails` field, so nothing "
                + "here is pinned to them: \(Set(keys.asDecoded).subtracting(fields).sorted()) "
                + "(the golden spells its keys \(keys.asWritten.sorted())). Add a `RejectDetails` "
                + "field AND a comparison above — the field alone turns this test green while "
                + "leaving the entry uncompared, which this check cannot see — or drop the entry "
                + "from `ConfigSetRejectDetails` (src/config/settings.rs) and re-emit the golden"
        )
    }

    /// Non-degeneracy. All three PARITY assertions above would pass over a golden of empty strings
    /// if the Swift copies were empty too, and would pass over a golden whose entries had been
    /// swapped. Anchor each on the token it must name — the offending KEY and the field name, never
    /// the part that drifts — so this is a liveness check, not another copy of the messages.
    func testTheGoldenIsNotDegenerate() throws {
        let golden = try committed()
        XCTAssertTrue(
            golden.configSetErrorStaleKey.contains("session_trigger")
                && golden.configSetErrorStaleKey.contains("`poll_secs`"),
            "the golden's stale-key entry names neither the offending key nor a settable: "
                + golden.configSetErrorStaleKey)
        XCTAssertTrue(
            golden.configSetRejectedFleetRunwayInvalid.hasPrefix("fleet_runway_warn_secs"),
            "the golden's fleet-runway entry does not lead with its field: "
                + golden.configSetRejectedFleetRunwayInvalid)
        XCTAssertTrue(
            golden.zeroTargetRemedyDetail.hasPrefix("target_max_session_usage")
                && golden.zeroTargetRemedyDetail.contains("session_ceiling"),
            "the golden's zero-target entry names neither the offending field nor the one it "
                + "redirects to: " + golden.zeroTargetRemedyDetail)
    }
}
