// Copyright (c) 2026 Oleksii PELYKH
// SPDX-License-Identifier: MIT

// The Swift half of the config-set reject-detail cross-language pin (issue #1112).
//
// Three Swift copies hold a `detail` that is a VERBATIM copy of a message the Rust crate authors.
// Two are `Fixtures` entries — `configSetErrorStaleKey` (serde's `deny_unknown_fields` message for
// `SetTunables`, which enumerates every settable key) and `configSetRejectedFleetRunwayInvalid`
// (`Config::validate`'s fleet-runway band rejection). The tests that consume those fixtures assert
// the client threads the daemon's own `detail` through instead of substituting a generic one, and
// they are green whether or not the copy is current: the fixture IS their oracle. So a stale copy
// still proved the plumbing, and nothing proved the fidelity the fixture exists for.
//
// The third (issue #1248) is `SettingsTextMetricsTests.zeroTargetRemedyDetail`: `Config::validate`'s
// `target_max_session_usage = 0` remedy (issue #414), held as a BARE `detail` string rather than a
// canned reply because its consumer measures rendered WIDTH, not decoding. Same defect class, same
// reason nothing caught it — the copy was its own oracle. It stays in that file rather than moving
// to `Fixtures.swift`, which is deliberately free of XCTest and app-model dependencies while this
// string must read its two key names from `TunableField`; it is `static` only so this gate can
// reach it.
//
// None of the three exists as a literal in `src/` — the fleet band is `format!`-interpolated from
// `FLEET_RUNWAY_PLAUSIBLE_MAX_SECS`, the key enumeration is generated by serde's derive, and the
// zero-target remedy interpolates the submitted `session_ceiling` — so they cannot be grepped for.
// All three are free at runtime, so `src/config/settings.rs` emits them into
// `build/fixtures/config-set-reject-details.json` and pins that file to what the code produces;
// this file reads the SAME bytes. Neither surface can move alone: change a message and the Rust pin
// reddens until the golden is re-emitted, and re-emitting reddens THIS gate until the copies
// follow. Same mechanism as `WireGoldenTests` (issue #340) and `CrossSurfaceSeverityParityTests`
// (issue #768).
//
// The zero-target emitter passes `DEFAULT_SESSION_CEILING` explicitly rather than letting the test
// config's own ceiling stand, because that message interpolates whatever ceiling was submitted and
// the Swift copy states it models the shipped default. A MOVE of that constant therefore reddens
// this gate too — the half of that copy no message-text edit would disturb.
//
// The golden is read from the repo, not bundled: the Swift copies deliberately stay inline literals
// in their own files, and the path resolves from THIS source file's `#filePath`, so it works
// identically under `xcodebuild test` in CI and locally with no working-directory assumption.
// `build/fixtures/**` is in the `swift` CI path filter, so re-emitting re-runs this check.
//
// What this gate does NOT reach, in both directions. It compares the `detail` STRING, not the
// envelope around it — the reply shape is `ConfigWireTests`' subject. It does not cover serde's
// input-dependent ` at line N column M` suffix, which `configSetErrorStaleKey` has elided since
// #671 and still elides; the golden is emitted position-free to match. It does not cover
// `configSetRejectedInvalid`, whose doc claims only that `detail` names the field — it is a
// synthetic sample, not a copy, and its wording does not match `validate.rs`'s current message. It
// does not cover `SettingsTextMetricsTests.staleKeyDetail`, which is RECONSTRUCTED from
// `TunableField.allCases` as a deliberate lower bound rather than copied. And it does not cover
// prose: a doc comment quoting a band (as `SettingsModelTests` does on
// `testApplyFleetRunwayOutOfBandRejectedWithDaemonDetail`) stays hand-maintained.
//
// That last file needs one more word, because naming only its prose understates it (issue #1248).
// The SAME test also asserts the fleet message IN FULL — a second verbatim copy of it, in the
// `XCTAssertEqual` on `applyPhase`. That copy is NOT unguarded and needs no pin of its own: it is
// asserted against `Fixtures.configSetRejectedFleetRunwayInvalid`, which IS pinned here, so it
// reddens the moment that fixture follows a re-emitted golden. Guarded transitively, not
// hand-maintained — the distinction naming only the prose would blur.
//
// One thing this gate DOES now reach that it did not (issue #1248): the golden's own key set.
// `RejectDetails` below and the Rust `ConfigSetRejectDetails` it mirrors both IGNORE unknown JSON
// keys, so a fourth entry emitted Rust-side used to decode clean on both sides and be read by
// nobody, with every test green. `testTheGoldenHasNoEntryThisGateDoesNotRead` compares the golden's
// top-level keys against the three read here, so such an entry reddens instead. Read its scope
// exactly: it proves no golden entry is missing from `readKeys`. It does NOT prove each read key is
// compared against a Swift copy — that stays enumerated, one test per key below — and it does NOT
// prove a name in `readKeys` reaches a `RejectDetails` field at all: adding a name here without the
// field and the comparison satisfies this test while leaving that entry unread. The opposite
// direction was already loud and stays so: a dropped or renamed key fails `RejectDetails`' decode
// here, and an empty golden fails the Rust pin's own decode before any comparison runs.
//
// Two bounds on that, both measured rather than assumed. It does not reach the RUST end of the same
// hole: `ConfigSetRejectDetails` (src/config/settings.rs) carries no `deny_unknown_fields`, and a
// golden holding an unread fourth key leaves that pin GREEN — only this side reddens. Reaching that
// end only matters for a hand-edited golden, which the repo already says to regenerate instead, so
// it is recorded here rather than closed. And it is a dedicated test rather than an unknown-key
// rejection inside `RejectDetails`' decode, which was the other way to close this: Swift has no
// `deny_unknown_fields`, so that route needs a hand-written `init(from:)` enumerating the very same
// key set — no more exhaustive-by-construction, and it would report a coverage gap as a DECODING
// failure in every test that touches `committed()`, burying which key is unread. This way one test
// reddens and names it.

import XCTest

final class ConfigSetRejectDetailParityTests: XCTestCase {

    /// The committed golden's shape. All three fields are non-optional ON PURPOSE: a renamed or
    /// dropped key fails the decode loudly instead of defaulting to an empty string that would then
    /// compare equal to nothing and pass. Unknown keys are the direction this shape does NOT catch —
    /// `testTheGoldenHasNoEntryThisGateDoesNotRead` below covers that one.
    private struct RejectDetails: Decodable {
        let configSetErrorStaleKey: String
        let configSetRejectedFleetRunwayInvalid: String
        let zeroTargetRemedyDetail: String
    }

    /// Just enough of a reply envelope to lift the copied string out of a fixture. Deliberately NOT
    /// `decodeConfigSetReply`: this gate is about the string, and routing it through the production
    /// decoder would make a decoder bug able to mask a drifted fixture.
    private struct DetailEnvelope: Decodable {
        let detail: String
    }

    /// Repo-root `build/fixtures/config-set-reject-details.json` resolved from this test file's own
    /// location — the same idiom as `WireGoldenTests`. Strips the filename then three directory
    /// levels (`Tests` → `menubar` → `apps`) to reach `<repo>/`.
    private static func goldenURL(file: StaticString = #filePath) -> URL {
        URL(fileURLWithPath: "\(file)")
            .deletingLastPathComponent()   // Tests/
            .deletingLastPathComponent()   // menubar/
            .deletingLastPathComponent()   // apps/
            .deletingLastPathComponent()   // <repo>/
            .appendingPathComponent("build/fixtures/config-set-reject-details.json")
    }

    /// The golden keys this gate reads — one per `RejectDetails` field above, spelled as they
    /// appear in the JSON. `committed()` decodes with `.convertFromSnakeCase`; the cardinality
    /// check below compares raw keys, so these stay snake case. A name here with no entry in the
    /// golden fails that check, and a `RejectDetails` field with no entry in the golden fails the
    /// decode. This list can still disagree with `RejectDetails` in ONE direction, and nothing
    /// here catches it: a name added here AND to the golden, with no matching field and no
    /// comparison below, passes both. Keeping the two in step is a hand discipline — add all
    /// three at once, per the failure message on the cardinality check.
    private static let readKeys: Set<String> = [
        "config_set_error_stale_key",
        "config_set_rejected_fleet_runway_invalid",
        "zero_target_remedy_detail",
    ]

    private func committed() throws -> RejectDetails {
        let url = Self.goldenURL()
        let data = try Data(contentsOf: url)
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try decoder.decode(RejectDetails.self, from: data)
    }

    private func detail(of fixture: String, _ name: String) throws -> String {
        let data = try XCTUnwrap(fixture.data(using: .utf8), "\(name) is not UTF-8")
        return try JSONDecoder().decode(DetailEnvelope.self, from: data).detail
    }

    /// `configSetErrorStaleKey`'s `detail` is serde's key enumeration for `SetTunables`, so it goes
    /// stale on any settable ADDED or RENAMED — a far wider trigger than the fleet fixture's. This
    /// is the copy that had actually drifted when #1112 was filed.
    func testStaleKeyFixtureDetailMatchesTheRustGolden() throws {
        XCTAssertEqual(
            try detail(of: Fixtures.configSetErrorStaleKey, "configSetErrorStaleKey"),
            try committed().configSetErrorStaleKey,
            "configSetErrorStaleKey's detail drifted from the Rust-emitted golden — a settable was "
                + "added or renamed in SetTunables (src/config.rs). Re-run `cargo test -- --ignored "
                + "emit_config_set_reject_details_golden`, then paste the golden's "
                + "config_set_error_stale_key value into this fixture's detail"
        )
    }

    /// `configSetRejectedFleetRunwayInvalid`'s `detail` goes stale when `Config::validate`'s message
    /// changes — including a move of `FLEET_RUNWAY_PLAUSIBLE_MAX_SECS`, which the Rust side derives
    /// from the constant and this copy spells out as a literal. That is what issue #1076 hit.
    func testFleetRunwayFixtureDetailMatchesTheRustGolden() throws {
        XCTAssertEqual(
            try detail(of: Fixtures.configSetRejectedFleetRunwayInvalid,
                       "configSetRejectedFleetRunwayInvalid"),
            try committed().configSetRejectedFleetRunwayInvalid,
            "configSetRejectedFleetRunwayInvalid's detail drifted from the Rust-emitted golden — "
                + "Config::validate's fleet_runway_warn_secs rejection changed "
                + "(src/config/validate.rs). Re-run `cargo test -- --ignored "
                + "emit_config_set_reject_details_golden`, then paste the golden's "
                + "config_set_rejected_fleet_runway_invalid value into this fixture's detail"
        )
    }

    /// `SettingsTextMetricsTests.zeroTargetRemedyDetail` is a BARE `detail` string, not a canned
    /// reply, so it is compared directly — there is no envelope to unwrap. It goes stale on any edit
    /// to `Config::validate`'s zero-target remedy AND on a move of `DEFAULT_SESSION_CEILING`, which
    /// that message interpolates and this copy spells out as a literal `1..=95` (issue #1248).
    func testZeroTargetRemedyMatchesTheRustGolden() throws {
        XCTAssertEqual(
            SettingsTextMetricsTests.zeroTargetRemedyDetail,
            try committed().zeroTargetRemedyDetail,
            "SettingsTextMetricsTests.zeroTargetRemedyDetail drifted from the Rust-emitted golden "
                + "— Config::validate's target_max_session_usage = 0 remedy changed, or "
                + "DEFAULT_SESSION_CEILING moved (src/config.rs). Re-run `cargo test -- --ignored "
                + "emit_config_set_reject_details_golden`, then paste the golden's "
                + "zero_target_remedy_detail value into that fixture"
        )
    }

    /// Issue #1248: coverage above is ENUMERATED — one test per entry — and nothing made it
    /// exhaustive. Both structs on this wire ignore unknown JSON keys, so an entry emitted
    /// Rust-side with no Swift copy pinned to it decoded clean and passed unread. Compare the key
    /// SETS rather than a count: a count is blind to a same-size rename, and the set names the
    /// offender in the failure.
    func testTheGoldenHasNoEntryThisGateDoesNotRead() throws {
        let raw = try JSONDecoder().decode(
            [String: String].self, from: Data(contentsOf: Self.goldenURL()))
        let present = Set(raw.keys)
        XCTAssertEqual(
            present, Self.readKeys,
            "the committed golden's entries are not the ones this gate reads. Emitted but unread "
                + "(nothing here is pinned to these): \(present.subtracting(Self.readKeys).sorted()). "
                + "Read here but absent from the golden: "
                + "\(Self.readKeys.subtracting(present).sorted()). For an emitted-but-unread entry, "
                + "add a `RejectDetails` field, a `readKeys` name and a comparison above — or drop it "
                + "from `ConfigSetRejectDetails` (src/config/settings.rs) and re-emit. For one read "
                + "here but absent from the golden, re-emit the golden or drop the name"
        )
    }

    /// Non-degeneracy. All three PARITY assertions above would pass over a golden of empty strings
    /// if the Swift copies were empty too, and would pass over a golden whose entries had been
    /// swapped. Anchor each on the token it must name — the offending KEY and the field name, never
    /// the part that drifts — so this is a liveness check, not another copy of the messages.
    func testTheGoldenIsNotDegenerate() throws {
        let golden = try committed()
        XCTAssertTrue(
            golden.configSetErrorStaleKey.contains("session_trigger")
                && golden.configSetErrorStaleKey.contains("`poll_secs`"),
            "the golden's stale-key entry names neither the offending key nor a settable: "
                + golden.configSetErrorStaleKey)
        XCTAssertTrue(
            golden.configSetRejectedFleetRunwayInvalid.hasPrefix("fleet_runway_warn_secs"),
            "the golden's fleet-runway entry does not lead with its field: "
                + golden.configSetRejectedFleetRunwayInvalid)
        XCTAssertTrue(
            golden.zeroTargetRemedyDetail.hasPrefix("target_max_session_usage")
                && golden.zeroTargetRemedyDetail.contains("session_ceiling"),
            "the golden's zero-target entry names neither the offending field nor the one it "
                + "redirects to: " + golden.zeroTargetRemedyDetail)
    }
}
